app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, UserMixin
from flask_bcrypt import Bcrypt
from flask_dance.consumer.storage.sqla import OAuthConsumerMixin
from sqlalchemy.orm.collections import attribute_mapped_collection


db = SQLAlchemy()
bcrypt = Bcrypt()


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(256), unique=True, nullable=False)
    password_hash = db.Column(db.LargeBinary, nullable=True)

    @property
    def password(self):
        raise AttributeError("password is not a readable attribute")

    @password.setter
    def password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password)

    @password.deleter
    def password(self):
        self.password_hash = None

    @property
    def has_password(self):
        return bool(self.password_hash)

    def verify_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)


class OAuth(OAuthConsumerMixin, db.Model):
    __table_args__ = (db.UniqueConstraint("provider", "provider_user_id"),)
    provider_user_id = db.Column(db.String(256), nullable=False)
    provider_user_login = db.Column(db.String(256), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    user = db.relationship(
        User,
        # This `backref` thing sets up an `oauth` property on the User model,
        # which is a dictionary of OAuth models associated with that user,
        # where the dictionary key is the OAuth provider name.
        backref=db.backref(
            "oauth",
            collection_class=attribute_mapped_collection("provider"),
            cascade="all, delete-orphan",
        ),
    )


# setup login manager
login_manager = LoginManager()
login_manager.login_view = "auth.login"


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, EqualTo
from sqlalchemy.exc import IntegrityError
from .models import db, User


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])

    def get_user(self):
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append("Username not found")
            return None
        if not user.verify_password(self.password.data):
            self.password.errors.append("Invalid password")
            return None
        return user


class RegisterForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            EqualTo("repeat_password", message="Passwords must match"),
        ],
    )
    repeat_password = PasswordField("Repeat Password")

    def create_user(self):
        user = User(username=self.username.data)
        user.password = self.password.data
        db.session.add(user)
        try:
            db.session.commit()
            return user
        except IntegrityError:
            self.username.errors.append("This username is already taken")
            return None


class SetPasswordForm(FlaskForm):
    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            EqualTo("repeat_password", message="Passwords must match"),
        ],
    )
    repeat_password = PasswordField("Repeat Password")

app/__init__.py
from flask import Flask
from .config import Config
from .models import db, bcrypt, login_manager
from .oauth import github_blueprint, google_blueprint
from .views import auth_blueprint, main_blueprint
from .cli import create_db, shell_context_processor


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.register_blueprint(github_blueprint, url_prefix="/login")
    app.register_blueprint(google_blueprint, url_prefix="/login")
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(main_blueprint)
    app.cli.add_command(create_db)
    app.shell_context_processors.append(shell_context_processor)
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    return app

app/oauth/__init__.py
from .github import blueprint as github_blueprint
from .google import blueprint as google_blueprint

app/views/__init__.py
from .auth import blueprint as auth_blueprint
from .main import blueprint as main_blueprint

app/views/auth.py
from flask import Blueprint, request, redirect, url_for, flash, render_template
from flask_login import login_required, login_user, logout_user, current_user
from app.models import db, User, OAuth
from app.forms import RegisterForm, LoginForm, SetPasswordForm


blueprint = Blueprint("auth", __name__)


@blueprint.route("/register", methods=("GET", "POST"))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = form.create_user()
        if user:
            login_user(user)
            flash("Account created")
            return redirect(url_for("main.index"))
    return render_template("register.j2", form=form)


@blueprint.route("/login", methods=("GET", "POST"))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = form.get_user()
        if user:
            login_user(user)
            flash("You have logged in")
            return redirect(url_for("main.index"))
    return render_template("login.j2", form=form)


@blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have logged out")
    return redirect(url_for("main.index"))


@blueprint.route("/set_password", methods=("GET", "POST"))
@login_required
def set_password():
    form = SetPasswordForm()
    if form.validate_on_submit():
        current_user.password = form.password.data
        db.session.add(current_user)
        db.session.commit()
        flash("Password set successfully")
        return redirect(url_for("main.index"))
    return render_template("set_password.j2", form=form)


@blueprint.route("/merge", methods=("GET", "POST"))
@login_required
def merge():
    form = LoginForm(data={"username": request.args.get("username")})
    if form.validate_on_submit():
        user = form.get_user()
        if user:
            if user != current_user:
                merge_users(current_user, user)
                flash(
                    "User {username} has been merged into your account".format(
                        username=user.username
                    )
                )
                return redirect(url_for("main.index"))
            else:
                form.username.errors.append("Cannot merge with yourself")
    return render_template("merge.j2", form=form)


def merge_users(merge_into, merge_from):
    assert merge_into != merge_from
    OAuth.query.filter_by(user=merge_from).update({"user_id": merge_into.id})
    db.session.delete(merge_from)
    db.session.commit()
    return merge_into

app/views/main.py
from flask import Blueprint, render_template

blueprint = Blueprint("main", __name__)


@blueprint.route("/")
def index():
    return render_template("home.j2")

app/templates/base.j2
{% import 'macros.j2' as macros %}
<!DOCTYPE html>
<head>
    <title>{% block title %}Flask-Dance Multi Provider{% endblock %}</title>
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
</head>
<body>
  {{ macros.messages() }}
  {% block body %}{% endblock %}
</body>

app/templates/home.j2
{% extends 'base.j2' %}
{% block body %}
<h1>Home</h1>
{% if current_user.is_authenticated %}
  <p>You are logged in as <strong>{{ current_user.username }}</strong>!</p>
  <ul>
    <li>
      You{% if not current_user.has_password %} do not{% endif %} have a password set for your account.
      {% if not current_user.has_password %}
        <a href="{{ url_for("auth.set_password") }}">Set a password</a>
      {% endif %}
    </li>
    <li>
      {% if current_user.oauth["google"] %}
        You are <strong>{{ current_user.oauth["google"].provider_user_login }}</strong> on Google.
      {% else %}
        You have not linked a Google account.
        <a href="{{ url_for("google.login") }}">Link Google account</a>
      {% endif %}
    </li>
    <li>
      {% if current_user.oauth["github"] %}
        You are <strong>{{ current_user.oauth["github"].provider_user_login }}</strong> on GitHub.
      {% else %}
        You have not linked a GitHub account.
        <a href="{{ url_for("github.login") }}">Link GitHub account</a>
      {% endif %}
    </li>
  </ul>
  <a href="{{ url_for("auth.logout") }}">Log out</a>
{% else %}
  You are not logged in.
  <a href="{{ url_for("auth.login") }}">Log in</a>
{% endif %}
{% endblock %}

app/templates/login.j2
{% extends 'base.j2' %}
{% import 'macros.j2' as macros %}
{% block body %}
  <h1>Login</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ macros.render_field(form.username) }}
    {{ macros.render_field(form.password) }}
    <div class="buttons">
      <input type="submit" value="Log In">
    </div>
  </form>
  <p>OR</p>
  <ul>
    <li><a href="{{ url_for("github.login") }}">Login with GitHub</a></li>
    <li><a href="{{ url_for("google.login") }}">Login with Google</a></li>
  </ul>
  <p>If you want to create a new account, log in with a social provider or
    <a href="{{ url_for("auth.register") }}">go to the registration page</a>.
  </p>
{% endblock %}

app/templates/macros.j2
{% macro messages() -%}
  {% set messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flash">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endmacro %}

{% macro render_field(field) -%}
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="errors">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endmacro %}

app/templates/merge.j2
{% extends 'base.j2' %}
{% import 'macros.j2' as macros %}
{% block body %}
  <h1>Merge Account</h1>
  <p>If you want to merge another account into this one, log in to that account here. That account must have a password set.</p>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ macros.render_field(form.username) }}
    {{ macros.render_field(form.password) }}
    <div class="buttons">
      <input type="submit" value="Merge Account">
    </div>
  </form>
  <p>Warning: all of the content of that account will be transferred to this account, and then that account will be deleted!</p>
{% endblock %}

app/templates/register.j2
{% extends 'base.j2' %}
{% import 'macros.j2' as macros %}
{% block body %}
  <h1>Register</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ macros.render_field(form.username) }}
    {{ macros.render_field(form.password) }}
    {{ macros.render_field(form.repeat_password) }}
    <div class="buttons">
      <input type="submit" value="Register">
    </div>
  </form>
  <p>If you want to login instead,
    <a href="{{ url_for("auth.login") }}">go to the login page</a>.
  </p>
{% endblock %}

app/templates/set_password.j2
{% extends 'base.j2' %}
{% import 'macros.j2' as macros %}
{% block body %}
  <h1>Set Password</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ macros.render_field(form.password) }}
    {{ macros.render_field(form.repeat_password) }}
    <div class="buttons">
      <input type="submit" value="Set Password">
    </div>
  </form>
{% endblock %}